# Generated by Django 2.1.5 on 2019-03-02 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20190302_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='when',
        ),
    ]
