# Generated by Django 2.1.5 on 2019-03-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_conductor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryPedido', models.CharField(max_length=20)),
                ('titlePedido', models.CharField(max_length=20)),
                ('pricePedido', models.CharField(max_length=20)),
                ('minimalPedido', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Conductor',
        ),
    ]
